# -*- coding: utf-8 -*-
"""Stock Trend Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmUJ9bHCeu_h65souN1S0TEmUfZb2J0p
"""


# Import libraries
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Choose stock (example: Apple)
stock = "AAPL"

# Download data
data = yf.download(stock, start="2024-01-01", end="2025-01-01")

# Show first 5 rows
data.head()

plt.figure()
plt.plot(data['Close'])
plt.title(f"{stock} Closing Price")
plt.xlabel("Date")
plt.ylabel("Price")
plt.show()

# Calculate Moving Averages
data['MA_5'] = data['Close'].rolling(window=5).mean()
data['MA_20'] = data['Close'].rolling(window=20).mean()

# Plot
plt.figure()
plt.plot(data['Close'], label="Close Price")
plt.plot(data['MA_5'], label="5-Day MA")
plt.plot(data['MA_20'], label="20-Day MA")

plt.title(f"{stock} Trend Analysis")
plt.legend()
plt.show()

# Get last values
last_ma5 = data['MA_5'].iloc[-1]
last_ma20 = data['MA_20'].iloc[-1]

if last_ma5 > last_ma20:
    print("📈 Uptrend (Bullish)")
elif last_ma5 < last_ma20:
    print("📉 Downtrend (Bearish)")
else:
    print("😐 Sideways Trend")

# Calculate RSI
delta = data['Close'].diff()

gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()

rs = gain / loss
data['RSI'] = 100 - (100 / (1 + rs))

# Plot RSI
plt.figure()
plt.plot(data['RSI'])
plt.axhline(70)
plt.axhline(30)
plt.title("RSI Indicator")
plt.show()

last_rsi = data['RSI'].iloc[-1]

if last_rsi > 70:
    print("🔴 Overbought → Sell Signal")
elif last_rsi < 30:
    print("🟢 Oversold → Buy Signal")
else:
    print("⚪ Neutral")



"""Multiple stocks"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Multiple stocks
stocks = ["AAPL", "GOOGL", "MSFT"]

# Download data
data = yf.download(stocks, start="2024-01-01", end="2025-01-01")['Close']

data.head()

plt.figure()

for stock in stocks:
    plt.plot(data[stock], label=stock)

plt.title("Stock Price Comparison")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()

#NORMALIZE DATA as price different so comparison unfair
normalized_data = data / data.iloc[0] * 100

plt.figure()

for stock in stocks:
    plt.plot(normalized_data[stock], label=stock)

plt.title("Normalized Comparison (Performance %)")
plt.legend()
plt.show()

returns = normalized_data.iloc[-1]

best_stock = returns.idxmax()
print(f"🏆 Best Performing Stock: {best_stock}")

for stock in stocks:
    data[f"{stock}_MA20"] = data[stock].rolling(20).mean()

plt.figure()

for stock in stocks:
    plt.plot(data[f"{stock}_MA20"], label=f"{stock} MA20")

plt.title("Moving Average Comparison")
plt.legend()
plt.show()

import streamlit as st
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("📊 Stock Trend Analyzer")

# Input stocks
stocks = st.text_input("Enter stock symbols (comma separated)", "AAPL,MSFT,GOOGL")
stock_list = [s.strip() for s in stocks.split(",")]

# Date range
start_date = st.date_input("Start Date", pd.to_datetime("2022-01-01"))
end_date = st.date_input("End Date", pd.to_datetime("2024-01-01"))

# Fetch data
if st.button("Analyze"):
    data = yf.download(stock_list, start=start_date, end=end_date)['Close']

    st.subheader("📈 Price Comparison")
    st.line_chart(data)

    # Normalize
    normalized = data / data.iloc[0] * 100

    st.subheader("⚖️ Normalized Comparison (Performance)")
    st.line_chart(normalized)

    # Trend logic
    st.subheader("🧠 Trend Analysis")

    for stock in stock_list:
        ma5 = data[stock].rolling(5).mean().iloc[-1]
        ma20 = data[stock].rolling(20).mean().iloc[-1]

        if ma5 > ma20:
            st.write(f"{stock}: 📈 Uptrend")
        elif ma5 < ma20:
            st.write(f"{stock}: 📉 Downtrend")
        else:
            st.write(f"{stock}: 😐 Sideways")

    # Best performer
    returns = normalized.iloc[-1]
    best_stock = returns.idxmax()

    st.success(f"🏆 Best Performing Stock: {best_stock}")



